export const RECEIVE_LOGOUT = "RECEIVE_LOGOUT";
export const RECEIVE_SESSION = "RECEIVE_SESSION";
export const RECEIVE_SESSION_ERROR = "RECEIVE_SESSION_ERROR";
export const RECEIVE_LOGOUT_ERROR = "RECEIVE_LOGOUT_ERROR";
